### ISSUE TITLE
TODO 2.0 launch

### ISSUE THREAD

**Issue by javierarce** [PopulateTools/gobierto.es#37]
- [x] Grab screen captures of modules.
- [x] Add screen captures of modules.
- [x] Add art/capture to the browser in the home page cover.
- [x] Create blog template.
- [x] Review needed text for each module (home and module page)
- [x] Implement "modules" section.
- [x] Make feature module dynamic.
- [x] Create page for each module.
- [x] Enable main navigation.
- [x] Migrate mockup page to jekyll.
- [x] Add links to client logos.
- [x] Implement Module tooltip.
- [x] Add minimal form validation in the contact form.
- [x] Add minimal form validation in the demo form.
- [x] Add links to footer items.

**Comment by javierarce** [comment]
Closing this. I'll create new issues for the pending tasks.
